# Generated by Django 4.1.5 on 2023-03-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
