# Generated by Django 4.1.5 on 2023-03-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image_produtc',
            field=models.ImageField(max_length=520, upload_to='static/images/product_gallery'),
        ),
    ]
