# Generated by Django 4.1.5 on 2023-03-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_productgallery_image_produtc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image_produtc',
            field=models.ImageField(max_length=520, upload_to='photos/product_gallery'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('COLOR', 'color'), ('SIZE', 'size')], max_length=200),
        ),
    ]
