# Generated by Django 4.1.5 on 2023-02-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='price',
            new_name='quantity',
        ),
    ]
