# Generated by Django 4.1.5 on 2023-02-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_variation_variation_category'),
        ('carts', '0003_alter_cartitems_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='varation',
            field=models.ManyToManyField(blank=True, to='product.variation'),
        ),
    ]
