# Generated by Django 4.1.5 on 2023-02-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitems_varation'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
