# Generated by Django 4.1.5 on 2023-03-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_number',
            new_name='first_name',
        ),
    ]
