# Generated by Django 4.1.5 on 2023-03-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_oredered',
            field=models.BooleanField(default=False),
        ),
    ]
